version: '3.11'

services:

  redis:
    image: redis:7.0.11-alpine

  django:
    container_name: shop
    build:
      context: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./db.sqlite3:/opt/app/db.sqlite3
    ports:
      - 8000:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-vo&v6)zt$tfddt^xhc_yq2_1&9+dd-=9y0n2!^jda^rsr7h=*k
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./
    command: celery --app=myshop worker -l INFO -P threads -B
    volumes:
      - ./db.sqlite3:/opt/app/db.sqlite3
    environment:
      - DEBUG=1
      - SECRET_KEY=django-insecure-vo&v6)zt$tfddt^xhc_yq2_1&9+dd-=9y0n2!^jda^rsr7h=*k
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django



